spring.application.name=course-management

# DATABASE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management
spring.datasource.username=postgres
spring.datasource.password=123

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# SQL LOG
spring.jpa.show-sql=true
